#################################
#           animations          #
#################################
animations = (
  {
    triggers = ["close", "hide"];
    preset = "disappear";
    duration = 0.16;
    scale = 1.0;
  },
  {
    triggers = ["open", "show"];
    preset = "appear";
    duration = 0.16;
    scale = 0.98;
  }
);
#################################
#             shadows           #
#################################
shadow = true;
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.4;
shadow-exclude = [
  "name = 'notification'",
  "class_g ?= 'notify-osd'",
  "_gtk_frame_extents@:c",
];

#################################
#           fading              #
#################################
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 4;

#################################
#   transparency / opacity      #
#################################
# standard opacity
active-opacity = 1.0;
inactive-opacity = 0.85;
frame-opacity = 1.0;

inactive-opacity-override = false;

focus-exclude = [ 
  "class_g = 'brave-browser'",
  "class_g = 'gimp'",
];

opacity-rule = [
  "100:class_g    = 'brave-browser'",
  "100:class_g    = 'gimp'",
  "75:class_g     = 'kitty'",
  "85:class_g     = 'rofi'",
  "85:class_g     = 'music'"
];

#################################
#     background blurring       #
#################################
blur-method = "dual_kawase";
blur-strength = 4;
blur-background = true;
blur-background-frame = false;
blur-background-fixed = false;

blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_gtk_frame_extents@:c",
];

#################################
#       general settings        #
#################################
backend = "glx";
vsync = true;
mark-wmwin-focused = true;
mark-ovlp-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
use-damage = true;
log-level = "warn";

wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = false; };
  dock = { shadow = false; clip-shadow-above = true; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 0.8; }
  dropdown_menu = { opacity = 0.8; }
};
