#!/bin/bash
WALL_DIR="$HOME/dotfiles/oxwm-dotfile/walls"

LIST=""
while IFS= read -r file; do
  LIST+="${file}\0icon\x1f${WALL_DIR}/${file}\n"
done < <(find "$WALL_DIR" -mindepth 2 -type f -printf "%P\n")

SELECTION=$(echo -e "$LIST" | rofi -dmenu -i -p "OXWM Theme Control" \
  -show-icons \
  -theme-str 'window { width: 50%; } listview { columns: 3; lines: 3; } element { orientation: vertical; } element-icon { size: 150px; } element-text { horizontal-align: 0.5; }')

if [ -n "$SELECTION" ]; then
  ln -sf "$WALL_DIR/$SELECTION" "$HOME/.local/share/current_wallpaper"
  xwallpaper --zoom "$HOME/.local/share/current_wallpaper"
  wal -i "$HOME/.local/share/current_wallpaper" -n -q
  ln -sf ~/.cache/wal/oxwm-colors.lua ~/.config/oxwm/colors.lua
  betterlockscreen -u "$HOME/.local/share/current_wallpaper" --fx blur &
  pgrep oxwm && xdotool key super+shift+r
  notify-send -i "$WALL_DIR/$SELECTION" "OXWM Theme Control" "Wallpaper changed"
fi
