color0 #1b1c22
color1 #fd4663
color2 #6775e4
color3 #8c5cd6
color4 #c166cc
color5 #939dec
color6 #b696e9
color7 #f2f2f3
color8 #64667a
color9 #fd4663
color10 #6775e4
color11 #8c5cd6
color12 #c166cc
color13 #939dec
color14 #b696e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1b1c22
background            #1b1c22
foreground            #f2f2f3
selection_foreground  #afafb6
selection_background  #24252d
active_border_color   #6775e4
inactive_border_color #24252d
url_color             #6775e4
